### ISSUE TITLE
--version required input file, but --help not

### ISSUE THREAD

**Issue by vitalyzhakov** [jetstyle/styletto#1]
~/testrepo/dom-services/blocks$ styletto --version

Error: You need to send config or style file.
~/testrepo/dom-services/blocks$ styletto --help

Usage: styletto [options] inputFile [outputFile]

Options:

-c            Compress output file using csso
-b            Encode images to base64
-h, --help    Display help information

This issue has little-little priority.

**Comment by iAdramelk** [comment]
Fixed in 0.3.0
